/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Public company form submission */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublicSubmissionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a file (pre-submission)
         * @description Accepts a single file under field name `file`. Max size 10MB. Allowed types: application/pdf, image/png, image/jpeg.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Uploaded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadFileResponse"];
                    };
                };
                /** @description Invalid file */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unprocessable file */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an uploaded (unattached) file
         * @description Allows clients to abandon and delete a previously uploaded file by its uploadId.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uploadId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies (aggregated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export submissions to CSV by date range */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicSubmissionRequest: {
            name: string;
            code: string;
            country: string;
            legalForm: string;
            address: string;
            registry: string;
            eDeliveryAddress: string;
            /** Format: date */
            reportingFrom: string;
            /** Format: date */
            reportingTo: string;
            contactName: string;
            /** Format: email */
            contactEmail: string;
            contactPhone: string;
            requirementsApplied: boolean;
            requirementsLink?: string;
            organs?: components["schemas"]["OrganRow"][];
            genderBalance: components["schemas"]["GenderBalanceRow"][];
            measures?: components["schemas"]["Measure"][];
            attachments?: components["schemas"]["AttachmentRef"][];
            reasonsForUnderrepresentation?: string;
            consent: boolean;
            consentText: string;
            submitter: components["schemas"]["Submitter"];
            captchaToken: string;
        };
        OrganRow: {
            /** @enum {string} */
            organType: "VALDYBA" | "STEBETOJU_TARYBA";
            /** Format: date */
            lastElectionDate: string;
            /** Format: date */
            plannedElectionDate: string;
        };
        GenderBalanceRow: {
            /** @enum {string} */
            role: "CEO" | "BOARD" | "SUPERVISORY_BOARD";
            women: number;
            men: number;
            total: number;
        };
        Measure: {
            name: string;
            plannedResult: string;
            indicator?: string;
            indicatorValue?: string;
            indicatorUnit?: string;
            year?: string;
        };
        AttachmentLink: {
            /** @enum {string} */
            type: "LINK";
            url: string;
        };
        AttachmentFileRef: {
            /** @enum {string} */
            type: "FILE";
            uploadId: string;
        };
        AttachmentRef: components["schemas"]["AttachmentLink"] | components["schemas"]["AttachmentFileRef"];
        UploadFileResponse: {
            uploadId: string;
            fileName: string;
            contentType: string;
            fileSize: number;
            storageKey: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Submitter: {
            name: string;
            title?: string;
            phone: string;
            /** Format: email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
